config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # Root path
  root to: 'items#index'

  # Health check route
  get 'up', to: 'rails/health#show', as: :rails_health_check

  # PWA-related routes
  get 'service-worker', to: 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest', to: 'rails/pwa#manifest', as: :pwa_manifest

  # User authentication
  devise_for :users

  # User routes
  resources :users, only: [] do
    resources :items, only: [:create]
    get :bookings, to: 'bookings#user_bookings', as: :bookings
  end

  # Items routes
  resources :items, only: [:index, :show, :new, :create, :destroy] do
    # Nested bookings routes under items
    resources :bookings, only: %i[new create]
  end

  # Dashboard route
  get 'dashboard', to: 'items#dashboard', as: :dashboard

  # Bookings routes
  resources :bookings, only: %i[index show edit update destroy] do
    # Route for owner's bookings
    collection do
      get 'owner', to: 'bookings#owner_index'
    end

    # Route to update booking status
    member do
      patch :update_status
    end
  end

  # My bookings
  get 'my_bookings', to: 'bookings#my_bookings', as: :my_bookings

  # Search for items
  get 'items/search', to: 'items#search', as: :search_items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  # Associations
  belongs_to :renter, class_name: 'User'
  belongs_to :item
  has_one :owner, through: :item

  # Validations
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date

  private

  # Validation personnalisée pour vérifier que la date de fin est après la date de début
  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date <= start_date
      errors.add(:end_date, "doit être après la date de début")
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  include PgSearch::Model

  belongs_to :owner, class_name: "User"
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true
  validates :description, presence: true
  validates :photo, presence: true

  pg_search_scope :search_by_name_and_description,
                  against: {
                    name: 'A',
                    description: 'B'
                  },
                  using: {
                    tsearch: { prefix: true } # Recherche partielle (ex : "arro" matchera "arrosoir")
                  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, foreign_key: :renter_id
  has_many :items, foreign_key: :owner_id
  has_many :bookings_as_owner, through: :items, source: :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy update_status]
  before_action :set_item, only: %i[new create]
  before_action :authenticate_user!

  def index
    @bookings = current_user.bookings.includes(:item)
  end

  def show; end

  def new
    @booking = @item.bookings.build
  end

  def create
    @booking = @item.bookings.build(booking_params)
    @booking.renter = current_user

    if @booking.save
      redirect_to @booking, notice: 'Réservation créée avec succès ! En attente de validation par le propriétaire.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # Modification d'une réservation
  def edit; end

  # Mise à jour d'une réservation
  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Réservation mise à jour avec succès.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if authorized_user?(@booking)
      @booking.destroy
      redirect_to bookings_path, notice: 'Réservation supprimée avec succès.'
    else
      redirect_to bookings_path, alert: 'Vous n\'êtes pas autorisé à supprimer cette réservation.'
    end
  end

  def user_bookings
    @user = User.find_by(id: params[:id])
    if @user
      @bookings = Booking.where(renter: @user)
    else
      redirect_to root_path, alert: 'Utilisateur non trouvé.'
    end
  end

  def update_status
    if authorized_user?(@booking)
      if @booking.update(status: params[:status])
        flash[:notice] = "Réservation mise à jour avec succès."
      else
        flash[:alert] = "Erreur lors de la mise à jour de la réservation."
      end
      redirect_back(fallback_location: dashboard_path)
    else
      redirect_to dashboard_path, alert: "Vous n'êtes pas autorisé à mettre à jour cette réservation."
    end
  end

  def my_bookings
    @bookings = current_user.bookings.includes(:item)
  end

  private

  # Définir la réservation en fonction de l'ID
  def set_booking
    @booking = Booking.find(params[:id])
  end

  # Définir l'item en fonction de l'ID
  def set_item
    @item = Item.find(params[:item_id])
  end

  # Autoriser uniquement les paramètres nécessaires
  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  # Vérifier si l'utilisateur actuel est autorisé à accéder à la réservation
  def authorized_user?(booking)
    current_user == booking.renter || current_user == booking.item.owner
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    if params[:query].present?
      @items = Item.search_by_name_and_description(params[:query])
    else
      @items = Item.all
    end
    @markers = @items.geocoded.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude,
        marker_html: render_to_string(partial: "marker"),
        info_window_html: render_to_string(partial: "info_window", locals: { item: item })
      }
    end
  end

  # Affiche un item spécifique
  def show
    @item = Item.find(params[:id])
    @booking = Booking.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.owner = current_user
    if @item.save
      redirect_to dashboard_path, notice: 'Objet ajouté avec succès !'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item mis à jour avec succès.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])

    if @item.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_path, notice: 'Item supprimé avec succès.' }
        format.turbo_stream
      end
    else
      flash[:alert] = 'Une erreur est survenue lors de la suppression de l\'item.'
      redirect_to dashboard_path
    end
  end

  def dashboard
    @items = current_user.items
    @bookings = Booking.joins(:item)
                       .where(items: { owner_id: current_user.id })
                       .where.not(status: 'rejected') # Exclut les refusées
                       .includes(:item)
  end

  private

  def set_item
    @item = Item.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to items_path, alert: "Item introuvable."
  end

  def item_params
    params.require(:item).permit(:name, :description, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(key)
    case key.to_s
    when 'notice' then 'info'    # Style Bootstrap pour info (bleu)
    when 'alert'  then 'warning' # Style Bootstrap pour alerte (jaune)
    when 'success' then 'success' # Style Bootstrap pour succès (vert)
    when 'error' then 'danger'   # Style Bootstrap pour erreur (rouge)
    else 'secondary'             # Style par défaut
    end
  end
end

app/views/bookings/_form.html.erb
<%= form_with(model: [item, booking], local: true) do |form| %>
  <div class="form-group">
    <%= form.label :start_date, "Date de début" %>
    <%= form.date_field :start_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :end_date, "Date de fin" %>
    <%= form.date_field :end_date, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.submit "Réserver", class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Modifier l'item</h1>
<%= render 'form', item: @item, booking: @booking %>
<%= link_to 'Retour', item_path(@item) %>

app/views/bookings/index.html.erb
<h1>Liste des réservations</h1>
<% @bookings.each do |booking| %>
  <div>
    <p>Réservation du : <%= booking.item.name %></p>
    <p>Date de début : <%= booking.start_date %></p>
    <p>Date de fin : <%= booking.end_date %></p>
    <%= link_to 'Voir', booking_path(booking) %>
    <%= link_to 'Modifier', edit_booking_path(booking) %>
    <%= link_to 'Supprimer', booking_path(booking), method: :delete, data: { confirm: 'Êtes-vous sûr ?' } %>
  </div>
<% end %>
<%= link_to 'Nouvelle réservation', new_item_booking_path %>

app/views/bookings/my_bookings.html.erb
<div class="container mt-5">
<h1>Mes réservations</h1>
<% pending_bookings = @bookings.select { |booking| booking.status == 'pending' } %>
<% if pending_bookings.any? %>
  <div class="list-group">
    <% pending_bookings.each do |booking| %>
      <div class="list-group-item d-flex justify-content-between align-items-center py-3">
        <!-- Contenu principal de la réservation -->
        <div>
          <h5 class="mb-1">Objet : <%= booking.item.name %></h5>
          <p class="mb-1">Date de début : <%= booking.start_date %> | Date de fin : <%= booking.end_date %></p>
          <small>Status : <%= booking.status.capitalize %></small>
        </div>

        <!-- Boutons d'action (facultatifs) -->
        <div class="btn-group ms-auto" style="gap: 10px;">
          <%= link_to 'Voir', booking_path(booking), class: 'btn btn-info btn-sm' %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>Vous n'avez aucune réservation en attente.</p>
<% end %>
</div>

app/views/bookings/new.html.erb
<div class="container mt-4">
<h1>Nouvelle réservation</h1>
<%= render 'form', item: @item, booking: @booking %>
<%= link_to 'Retour', root_path %>

<% if @booking.errors.any? %>
  <div class="error-messages">
    <h2><%= pluralize(@booking.errors.count, "erreur") %> empêchent cette réservation :</h2>
    <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
</div>

app/views/bookings/show.html.erb
<div class="container mt-4">
<h1>Détails de la réservation</h1>
<p>Date de début : <%= @booking.start_date %></p>
<p>Date de fin : <%= @booking.end_date %></p>
<p>Status : <%= @booking.status == 'pending' ? 'En attente de validation' : @booking.status.capitalize %></p>

<%= link_to 'mes reservations', my_bookings_path(@booking) %>
<%= link_to 'Retour à la liste', root_path %>
</div>

app/views/bookings/user_bookings.html.erb
<h1>Réservations de <%= @user.first_name %></h1>
<% if @bookings.any? %>
  <ul>
    <% @bookings.each do |booking| %>
      <li>
        <strong>Objet :</strong> <%= booking.item.name %> <br>
        <strong>Dates :</strong> <%= booking.start_date %> à <%= booking.end_date %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Aucune réservation trouvée pour cet utilisateur.</p>
<% end %>

app/views/items/_info_window.html.erb
<h1><%= item.name %></h1>
<p><%= item.description %></p>

app/views/items/_marker.html.erb
<%= image_tag "kiss.png", height: 60, width: 60, alt: "Logo" %>

app/views/items/dashboard.html.erb
<div class="container">
<h1 class="mt-4 mb-3"> Objets mis en location</h1>
<% if flash.any? %>
  <% flash.each do |key, message| %>
    <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show m-1" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>
<div class="cards-dashboard">
  <% @items.each do |item| %>
    <div id="item_<%= item.id %>" class="card-product-dashboard position-relative">
      <!-- Supprimer cet item -->
      <%= button_to '×', item_path(item),
                    method: :delete,
                    data: { turbo_confirm: "Êtes-vous sûr de vouloir supprimer cet objet ?" },
                    class: "delete-item-btn" %>
      <!-- Image de l'item -->
      <%= cl_image_tag item.photo.key if item.photo.present? %>
      <div class="card-product-infos-dashboard">
        <h2><%= item.name %></h2>
      </div>
    </div>
  <% end %>
</div>
<script>
  document.addEventListener("turbo:load", () => {
    console.log("Turbo chargé !");
  });
</script>
<div class="mt-4 mb-5">
  <%= link_to 'Ajouter un objet', new_item_path, class:'btn btn-primary' %>
</div>
<div class="container">
<h2>Liste des demandes de réservations</h2>
<% if @bookings.present? && @bookings.any? %>
  <div class="list-group">
    <% @bookings.each do |booking| %>
      <div class="list-group-item d-flex justify-content-between align-items-center py-3">
        <div>
          <h5 class="mb-1">Item : <%= booking.item.name %></h5>
          <p class="mb-1">
            Date de début : <%= booking.start_date %> | Date de fin : <%= booking.end_date %>
          </p>
          <small>Status : <%= booking.status.capitalize %></small>
        </div>
        <% if booking.status == "pending" %>
          <div class="btn-group ms-auto" style="gap: 10px; margin-right: 10px;">
            <%= button_to 'Accepter',
                          update_status_booking_path(booking, status: 'accepted', redirect_to: dashboard_path),
                          method: :patch,
                          class: "btn btn-success btn-sm px-4" %>
            <%= button_to 'Refuser',
                          update_status_booking_path(booking, status: 'rejected', redirect_to: dashboard_path),
                          method: :patch,
                          class: "btn btn-danger btn-sm px-4",
                          data: { confirm: "Êtes-vous sûr de vouloir rejeter cette réservation ?" } %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>
  <p>Vous n'avez aucune réservation pour le moment.</p>
<% end %>
</div>
</div>

app/views/items/destroy.turbo_stream.erb
<%= turbo_stream.remove "item_#{@item.id}" %>

app/views/items/index.html.erb
 <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1072824/pexels-photo-1072824.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);">
      <div class="d-flex justify-content-center align-self-end">
        <h4>Magic Garden</h4>
      </div>
      <div class="d-flex justify-content-center align-self-end">
        <p>Cultivez votre vie, comme vous cultivez votre jardin</p>
        </div>
</div>


<div class="container">
<%# BARRE DE RECHERCHE  %>
  <div class="row justify-content-center mt-4 mb-3">
    <div class="col-sm-8 my-3">
      <%= form_tag items_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Rechercher"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<%# MAP %>
  <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

<%# grid avec les items %>
<div class="container">
  <div class="cards m-4">
    <% @items.each do |item| %>
      <div class="card-product">
         <%= cl_image_tag item.photo.key %>
        <div class="card-product-infos">
          <h2><%= item.name %></h2>
          <span><%= item.price %> €</span>
          <%# if item.available == "available" %>
          <%#   <span>available</span> %>
          <%#   <%= link_to 'Louer cet objet', new_item_booking_path(item), class: 'btn btn-primary' %>
          <%# elsif item.available == "pending" %>
          <%#   <span>pending</span> %>
          <%#   <div class="btn btn-pending">En attente</div> %>
          <%# elsif item.available == "not available" %>
          <%#   <span>not available</span> %>
          <%#   <div class="btn btn-not-available">Indisponible</div> %>
          <%# end %>
           <%= link_to 'Voir cet objet', item_path(item), class: 'btn btn-primary mt-3' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="container">
  <h1 class="mt-4 mb-5">Nouvel objet à mettre en location</h1>

<%= simple_form_for(@item) do |f| %>
  <%= f.input :name, label: "Nom de l'objet" %>
  <%= f.input :description, label: "Description" %>
  <%= f.input :price, label: "Prix" %>
  <%= f.input :photo, label: "Photo", as: :file %>

  <%= f.button :submit, "Ajouter" %>
<% end %>

app/views/items/show.html.erb
<div class="container mt-4">
  <div class="card shadow">
    <div class="card-header text-center">
      <h1 class="fw-bold"><%= @item.name %></h1>
    </div>
    <div class="card-body">
      <div class="row align-items-center">
        <!-- Colonne gauche : Image et informations de l'objet -->
        <div class="col-md-6 text-center p-4">
          <%= cl_image_tag @item.photo.key, height: 400, width: 400, crop: :fill, class: "rounded" %>
          <div class="mt-4">
            <p class="mb-2"><strong>Description :</strong> <%= @item.description %></p>
            <p><strong>Prix :</strong> <%= number_to_currency(@item.price) %></p>
          </div>
        </div>

        <!-- Colonne droite : Formulaire de réservation -->
        <div class="col-md-6 p-4">
          <h2 class="mb-4 text-center">Nouvelle réservation</h2>
          <%= render 'bookings/form', item: @item, booking: @booking %>

          <!-- Affichage des erreurs éventuelles -->
          <% if @booking.errors.any? %>
            <div class="alert alert-danger mt-4">
              <h4><%= pluralize(@booking.errors.count, "erreur") %> empêchent cette réservation :</h4>
              <ul>
                <% @booking.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card-footer text-center">
      <%= link_to 'Retour à la liste', items_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for(:title) || "Magic Garden" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Liste des items</h1>
<% @items.each do |item| %>
  <p><%= link_to item.name, item_path(home) %></p>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= flash_class(key) %> alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://st.depositphotos.com/1719108/3701/i/450/depositphotos_37011409-stock-illustration-watering-can.jpg", alt: "Magic Garden Logo" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          </li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item me-3">
            <span class="nav-link">
              Bienvenue <strong><%= current_user.first_name %></strong>
            </span>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://api.dicebear.com/6.x/thumbs/svg?seed=#{current_user.id}",
                          class: "avatar dropdown-toggle",
                          id: "navbarDropdown",
                          data: { bs_toggle: "dropdown" },
                          'aria-haspopup': true,
                          'aria-expanded': false,
                          alt: "Avatar de #{current_user.first_name}" %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mes réservations", my_bookings_path, class: "dropdown-item" %>
              <%= link_to "Mon tableau de bord", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %>
            </div>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-primary text-white" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>